def code_dict():
    data_dict = {
        '1763': 'VAT receivables',
        '2939': 'VAT liability',
        '2948': 'Tax account',
        '3000': 'Sales',
        '3380': 'Sales outside EU',
        '4000': 'Purchases',
        '4450': 'Subcontracts 1',
        '5430': 'Telephone benefits',
        '5600': 'Management salaries',
        '5990': 'Counter account of fringe benefits',
        '6300': 'Social security payments',
        '6400': 'Accident insurnce fees',
        '7000': 'Training of personnel',
        '7050': 'Occupational health service',
        '7110': 'Coffee accessories',
        '7120': 'Work clothes',
        '7130': 'Protective equipment',
        '7470': 'Other expenses of premises',
        '7520': 'Rent on vehicles',
        '7530': 'Fuel of vehicles',
        '7540': 'Service of vehicles',
        '7550': 'Tyres and car accessories',
        '7560': 'Public payments of vehicles',
        '7570': 'Vehicle insurances',
        '7690': 'Purchase of computer accessories',
        '7800': 'Tickets',
        '7820': 'Hotel and other accommodation',
        '7840': 'Travel insurance',
        '7850': 'Parking costs',
        '7870': 'Kilometre allowance',
        '7880': 'Daily allowance',
        '7890': 'Daily allowance abroad',
        '8330': 'Certification and quality certificates',
        '8380': 'Accounting services',
        '8420': 'Collecting and credit status services',
        '8440': 'Public payments',
        '8510': 'Mobile telephone costs',
        '8530': 'Data transfer costs',
        '8560': 'Money transaction costs',
        '8570': 'Rounding differences',
        '8580': 'Liability insurances',
        '8600': 'Other insurances',
        '8620': 'Office equipment',
        '8650': 'Meeting and negotiation costs',
        '9540': 'Penal interest on taxes',
        '9550': 'Other interest expenses',
        '9610': 'Collection expenses',
        '9900': 'Advance tax'
    }
    return data_dict

